### ISSUE TITLE
Possible namespace issue.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/oembed#2]
Hey @BWPanda, if this is not a straight port of https://www.drupal.org/project/oembed to Backdrop, then this will most likely cause namespace issues when/if people decide to actually port the D7 module over to Backdrop. Care to clarify please?

Thanks

**Comment by ghost** [comment]
Oh right. No, this module is integration for the oEmbed CKEditor plugin: https://ckeditor.com/cke4/addon/oembed

Might have to rename this one then...

**Comment by opi** [comment]
I guess most of ckeditor plugin module have the following namespace: ckeditor_pluginname (on my phone, can't add links, sorry)

**Comment by quicksketch** [comment]
+1 Renaming to CKEditor OEmbed would be appropriate.

**Comment by ghost** [comment]
What's the (best) process for renaming a module...?

**Comment by ghost** [comment]
I mean, is there any way to provide an upgrade path, or do users just have to know to disable the old module and enable the new one?

**Comment by ghost** [comment]
I'm going to close this due to lack of information about how best to do this, and of a need to do it. If the D7 module is ever ported, we can re-visit this then.
