### ISSUE TITLE
Can not key in the URL in Custom Block

### ISSUE THREAD

**Issue by simone960** [backdrop-contrib/oembed#3]
I try adding a custom block in the layout, but I can't paste or type on the "URL:" input field. There's no problem if I add a post/node of a content type. But it just don't work on the custom block. I'm testing on backdrop 1.8.0. Please advise. Thanks. 
 
![not working](https://user-images.githubusercontent.com/7530286/34240604-9544aac0-e663-11e7-95b2-f6e95d862444.png)

**Comment by ghost** [comment]
Thanks for reporting this!

It looks to be a core bug as the same thing happens with the Table CKEditor button (cannot edit fields there either). I've submitted a bug report here: https://github.com/backdrop/backdrop-issues/issues/2925

As it's not specific to this module, I'm closing this issue.

**Comment by simone960** [comment]
I see. No wonder... Glad you found the cause and hope it will be resolved soon as I love your module very much. Simple and yet useful. Thanks !
