### ISSUE TITLE
Automatically add iframe and div tags when this plugin is used

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/oembed#4]
I found that this plugin did not work unless div and iframe tags were added to the filtered HTML list. We can send this requirement to Backdrop so that it configures CKEditor and the filtered HTML filter to include these tags.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop-contrib/oembed/pull/5.

- To test, add a new text format. 
- Enable filtered HTML filter.
- Enable CKEditor on the format.
- Ensure any `<div>` and `<iframe>` tags are not allowed. 
- Drag in the oEmbed button.
- Check that `<div>` and `<iframe>` are automatically added for you in the tag list.

**Comment by ghost** [comment]
Thanks @quicksketch!

Is the `'attributes'` part necessary? I played with it, and couldn't see how it affects anything... Removing it doesn't prevents the tags be allowed or used, and restricting the attributes doesn't prevent others being added...

If it's not used/needed, I'd rather not have it there. If it's a bug though, perhaps we need to address that in core?

Also, you had
```php
'attributes' => array('data-align', 'data-oembed', 'data-resizetype', 'data-oembed_provider', 'class' => array('embeddedContent', 'oembed-provider-*')),
```
Shouldn't the class part be instead listed as
```php
'attributes' => array('data-align', 'data-oembed', 'data-resizetype', 'data-oembed_provider'),
'classes' => array('embeddedContent', 'oembed-provider-*'),
```
based on the documentation for `hook_ckeditor_plugins()`, or am I misinterpreting something?

**Comment by olafgrabienski** [comment]
> We can send this requirement to Backdrop so that it configures CKEditor and the filtered HTML filter to include these tags.

In my opinion it would be helpful to inform the site builder about newly allowed HTML tags.

**Comment by ghost** [comment]
@olafgrabienski I'll add a note to the README about this, but by default the following is displayed in the UI when tags are automatically added:

> Based on the text editor configuration, these tags have automatically been added: `<iframe>` `<div>`.

**Comment by olafgrabienski** [comment]
> by default the following is displayed in the UI when tags are automatically added

Interesting, @BWPanda! When / where is it displayed: after enabling the module?

**Comment by ghost** [comment]
Just below the field where the allowed tags are added/displayed.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/2385329/66768999-a7eb7880-eebc-11e9-9e30-49610ddcd933.png)

**Comment by ghost** [comment]
Fixed with https://github.com/backdrop-contrib/oembed/commit/200ad382d089cbcb2a2588cf4598ff6c7ff7515b.
